name: dester
description: "A new Flutter project."
publish_to: "none"
version: 0.3.0

environment:
  sdk: ^3.10.0

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.0
  dio: ^5.9.0
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.3
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  http: ^1.2.2
  logger: ^2.6.2
  lucide_icons_flutter: ^3.1.6
  mesh_gradient: ^1.3.8
  shared_preferences: ^2.3.3
  sliver_tools: ^0.2.12
  web_socket_channel: ^3.0.3
  window_manager: ^0.5.1
  flutter_form_builder: ^10.2.0
  super_context_menu: ^0.9.1
  multicast_dns: ^0.3.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  palette_generator_master: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
